name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'  # Keep consistent with local version
          channel: stable

      - name: Downgrade http to avoid web conflict
        run: |
          sed -i 's/^ *http: .*$/  http: ^1.1.0/' pubspec.yaml

      - name: Preserve go_router version
        run: |
          sed -i 's/^ *go_router: .*$/  go_router: 15.2.3/' pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: music-template-mkrjdo
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
